name: Upload Bundle to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  upload-cf-flat-decoder-ts-to-gh-pages:
    if: "contains(github.event.head_commit.message, 'release-please--branches--main')"
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ«¡ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.0

      - name: ğŸ§˜â€â™€ï¸ Download dependencies
        run: npm ci

      - name: ğŸ“¦ Build the cf-flat-decoder-ts bundle
        run: npm run build

      - name: ğŸ‘€ Lookup version
        run: |
          echo "VERSION=$(sed -n 's/.*\"version\": *\"\([^\"]*\)\".*/\1/p' package.json)" >> $GITHUB_ENV

      - name: ğŸ¨ Create version folder
        run: mkdir -p ${{ env.VERSION }}

      - name: ğŸ’ƒğŸ» Move files into the version folder
        run: |
          mv dist/index.js ${{ env.VERSION }}/index.js
          mv dist/index.js.map ${{ env.VERSION }}/index.js.map

      - name: ğŸ“… Publish latest version on gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          folder: ${{ env.VERSION }}
          target-folder: latest/

      - name: ğŸ¥ Publish explicit version on gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          folder: ${{ env.VERSION }}
          target-folder: ${{ env.VERSION }}/
